//
// BookISBNAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire



open class BookISBNAPI {
    /**
     Find book by ISBN
     
     - parameter ISBN: (path) ISBN code 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func isbnISBNGet(ISBN: String, completion: @escaping ((_ data: BookItem?,_ error: Error?) -> Void)) {
        isbnISBNGetWithRequestBuilder(ISBN: ISBN).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Find book by ISBN
     - GET /isbn/{ISBN}
     - examples: [{contentType=application/json, example={
  "Subtitle" : "Subtitle",
  "CoverThumb" : "data:image/jpeg;base64,/9j/2wCEAAgGBgcGBQgHBwcJCQgKDBQN...",
  "Description" : "Description",
  "ISBN" : "9789000035526",
  "Authors" : [ {
    "Name" : "Name"
  }, {
    "Name" : "Name"
  } ],
  "Title" : "Tobbe",
  "Subjects" : [ "Subjects", "Subjects" ],
  "LanguagCode" : "nl"
}}]
     
     - parameter ISBN: (path) ISBN code 

     - returns: RequestBuilder<BookItem> 
     */
    open class func isbnISBNGetWithRequestBuilder(ISBN: String) -> RequestBuilder<BookItem> {
        var path = "/isbn/{ISBN}"
        let ISBNPreEscape = "\(ISBN)"
        let ISBNPostEscape = ISBNPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{ISBN}", with: ISBNPostEscape, options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        
        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<BookItem>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

}
