//
// Author.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Author: Codable {

    public var name: String?

    public init(name: String?) {
        self.name = name
    }

    public enum CodingKeys: String, CodingKey { 
        case name = "Name"
    }


}

