//
// BookItem.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct BookItem: Codable {

    public var ISBN: String?
    public var title: String?
    public var languagCode: String?
    public var subtitle: String?
    /** the description of the book, empty if missing */
    public var _description: String?
    /** base64 encoded 200x200 scaled thumbnail of the front cover, empty if missing */
    public var coverThumb: String?
    public var subjects: [String]?
    public var authors: [Author]?

    public init(ISBN: String?, title: String?, languagCode: String?, subtitle: String?, _description: String?, coverThumb: String?, subjects: [String]?, authors: [Author]?) {
        self.ISBN = ISBN
        self.title = title
        self.languagCode = languagCode
        self.subtitle = subtitle
        self._description = _description
        self.coverThumb = coverThumb
        self.subjects = subjects
        self.authors = authors
    }

    public enum CodingKeys: String, CodingKey { 
        case ISBN
        case title = "Title"
        case languagCode = "LanguagCode"
        case subtitle = "Subtitle"
        case _description = "Description"
        case coverThumb = "CoverThumb"
        case subjects = "Subjects"
        case authors = "Authors"
    }


}

